# Homework Assignment 4

## Description

This week the homework will test your ability to use numpy and scipy for the manipulation of numerical data and statistical analysis. This assignment is made of two parts and counts 1.0 points towards the final grade.

## Assignment

Change the name of this notebook to “H4.\<id\>”, replacing \<id\> by your student id. Perform the steps of each part, each step should correspond to a different cell in your notebook. Don’t forget to properly comment and document all your code.

In [1]:
import numpy as np
import scipy as sp
import scipy.stats as stats

### Part I – Numpy Operations (0.2 points)

In the following cell create a 5x5 numpy array (i.e. five rows and five columns) filled with random numbers ranging between -10 and 10. Use the numpy random module. Values should be of type float32 rounded to the second decimal digit. <br/>
Save this array in variable M1;

In [2]:
# We are making use of the uniform method of the random function to draw random samples from -10 to 10 from a uniform distribution.
# we are also making use of the "round" function to round the samples to 2 decimal places
# We are using the "astype" function to convert the random samples to type float32
M1 = (np.round((np.random.uniform(low=-10, high=10, size=(5,5))),2)).astype(np.float32)

Show that all values in M1 are of the expected data type

In [3]:
# to print the data type of array M
M1.dtype

dtype('float32')

Using the slice operators print the 2x2 array that corresponds to the elements in 3rd and 4th rows and the 2nd and 3rd columns of M1

In [4]:
# slicing elements from the 3rd and 4th ros and 2nd and 3rd columns of array M
M1[2:4,1:3]

array([[-3.89, -6.8 ],
       [ 2.92,  4.04]], dtype=float32)

Extract from M1 the elements from the 4th row and save it in variable v1

In [5]:
v1 = M1[3,:]

Extract from M1 the elements from the 4th column and save it in variable v2

In [6]:
v2 = M1[:,3]

Compute, and print, the outer product between v1 and v2 using Numpy

In [7]:
# computing the outer product of v1 and v2
np.outer(v1,v2)

array([[-16.056002 ,  23.013601 ,  25.2213   , -51.914402 , -62.6853   ],
       [  7.0080004, -10.044801 , -11.0084   ,  22.6592   ,  27.360401 ],
       [  9.696    , -13.8976   , -15.2308   ,  31.3504   ,  37.854797 ],
       [ 18.624    , -26.6944   , -29.255201 ,  60.2176   ,  72.711205 ],
       [-16.536001 ,  23.7016   ,  25.9753   , -53.4664   , -64.559296 ]],
      dtype=float32)

Compute the inner product between v2 and v1 Numpy

In [8]:
# dot product between arrays v2 and v1 using numpy's inner function
np.inner(v2,v1)

-45.6733

Find the eigenvectors and eigenvalues of matrix M1, use the Scipy linear algebra module.

In [9]:
np.linalg.eig(M1)

(array([-4.0457807+10.053348j , -4.0457807-10.053348j ,
         4.2946296 +4.1944103j,  4.2946296 -4.1944103j,
         4.1723027 +0.j       ], dtype=complex64),
 array([[-0.01804044+0.05617191j, -0.01804044-0.05617191j,
          0.06329444-0.10247278j,  0.06329444+0.10247278j,
         -0.06303056+0.j        ],
        [ 0.67871124+0.j        ,  0.67871124-0.j        ,
          0.45539832-0.29489744j,  0.45539832+0.29489744j,
          0.62846565+0.j        ],
        [ 0.30820283+0.37933955j,  0.30820283-0.37933955j,
          0.27083126-0.06542697j,  0.27083126+0.06542697j,
          0.31591478+0.j        ],
        [-0.29061013-0.09912955j, -0.29061013+0.09912955j,
          0.2201368 +0.39338556j,  0.2201368 -0.39338556j,
          0.2711901 +0.j        ],
        [-0.1567194 +0.42206746j, -0.1567194 -0.42206746j,
          0.64054537+0.j        ,  0.64054537-0.j        ,
          0.6539968 +0.j        ]], dtype=complex64))

## Part II - Independent two-sample t-test (0.8 points)

In this part we will perform a $t$-test to determine whether there is a significant difference between the means of two groups. In this exercise, these groups will correspond to two sampled data sets from pre-defined probability distributions. <br/>

Since we have two groups of data, we will focus on the particular case of an <i>independent two-sample t-test</i>. The significance of this approach requires our data to fullfill two assumptions: 1) they have the same length/size ($n_1 = n_2 = n$); and 2) that they were sampled from normal distributions with the same variance ($\sigma^2_1 = \sigma^2_2$). <br/>
Note that there are extensions of the t-test that relax these assumptions, but that discussion is out of scope of this week homework. <br/>

Our null-hypothesis, the one we will try to falsify, is that the data was sampled from the same distribution. Hence, given our assumption that both groups are normal and have the same variance, we expect that the difference between the means to be zero, or close to zero. <br/>

To perform the <i>independent two-sample t-test</i> we need first to compute the t-statistics ($t$), which is given by:

\begin{equation}
    t = \frac{m_1 - m_2}{\sqrt{\frac{\sigma_1^2}{n}+\frac{\sigma_2^2}{n}}}
\end{equation}

where $\sigma_1$ and $\sigma_2$ is, respectively, the standard deviation of the first and second data groups; $n$ is the group size (recall that, $n_1 = n_2 = n$). Remember that the formula to compute the standard deviation ($\sigma$) is given by:

\begin{equation}
    \sigma_i^2 = \frac{\sum(x-m_i)^2}{n_i-1}
\end{equation}

where the sum goes over all sampled points. To correctly compute the standard deviation we need to divide by the effective number of degrees of freedom ($n_i -1$), where $1$ are the so called Delta Degrees of Freedom.

Start by creating two one dimension ndarray filled with $n$ random numbers sampled from a Normal/Gaussian Distribution with mean $m$ and standard deviation sigma. Use the module stats from the Scipy library to achieve this. Crate two samples (i.e. two arrays) of size 50 ($n$) with different means (e.g., 0.72 and 0.48) and the same standard deviation of 1.0. Save these samples in variables d1 and d2.<br/><br/>
Recall that you can use the method norm.rvs() from Scipy stats module to sample random numbers from a normal distribution (see the documentation at https://tinyurl.com/yd9z99fq to check how to pass arguments to obtain a sample from a normal distribution with the desired mean and standard deviation).

In [10]:
# sampling random numbers with a mean of 0.72 and standard deviation of 1.0
d1 = stats.norm.rvs(loc=0.72, scale=1.0, size=50)

In [11]:
# sampling random numbers with mean of 0.48 and standard deviation of 1.0
d2 = stats.norm.rvs(loc=0.48, scale=1.0, size=50)

Assign to variables m1 and m2 the means of d1 and d2, respectively. Use the methods already included with numpy array.

In [12]:
# finding the average of numbers in d1
m1 = np.mean(d1)
print(m1)

0.6663545615575616


In [13]:
# finding the average of numbers in d2
m2 = np.mean(d2)
print(m2)

0.6245511783899523


Compute the length of each sample and save it in n

In [14]:
# finding the number of elements in array d1
n1 = len(d1)
print(n1)

50


In [15]:
# finding the number of elements in array d2
n2 = len(d2)
print(n2)

50


Assign to variables s1 and s2 the standard deviations of d1 and d2, respectively. Use the methods already included with numpy array. Note that you need to pass the argument Delta Degrees of Freedom (ddof) with value equal to one.

In [16]:
# finding the standard deviation of d1 with 1 degree of freedom
s1 = np.std(d1,ddof=1)
print(s1)

1.0873181910678587


In [17]:
# finding the standard deviation of d2 with 1 degree of freedom
s2 = np.std(d2,ddof=1)
print(s2)

1.0369966017451222


Compute the $t$-statistics following the formula for $t$ shown above, use the values previously computed.

In [18]:
# computing the t-statistics
t_stat = (m1-m2)/(np.sqrt(((s1**2)/n1)+((s2**2)/n2)))
print(t_stat)

0.19673006785551045


Differences between means from samples of normally distributted data follow a particular distribution known as the student t-distribution. With that information, we are ready to calculate the p-value, which answers the question: "If the null hypothesis is true, what is the probability that we'd observe a more extreme test statistic in the direction of the alternative hypothesis than we did?"<br/>

In a nuttshell we are looking to compute the probabilities of all events that lie outside the interval defined by \[-t,t[ of the student t-distribution. The figure bellow illustrates this,
![title](figure1.png)
the x-axis depicts the t-statistics, and the curve illustrates the shape of the student t-distribution.
From Scipy stats module you can find a method $t$ to evalute the t-distribution. Check the documentation https://tinyurl.com/yc4xd2hb. The t-distribution has a bell shape, similar to the normal distribution, however values are less concentrated around the peak. The t-distribution arguments are the mean and the degrees of freedom (df).<br/>

Hence, our task would require us to perform an integration over $t$ to find the p-value. Note that, since we are dealing with a probability distribution, by definition an integration of the t-distribution over the entire domain of t equals 1. An alternative and easier approach is to use the Cumulative Distribution Function (cdf) of the student t-distribution. <br />

A CDF, in abstract, returns the probability that X will take a value less than or equal to x. Hence, by evaluating the CDF of the t-distribution at t we will get the probability we'd observe an event that conforms with the null hypothesis. Subtracting this value to one will return the one-tailed p-value, the two-tailed, which is the one we are looking for, is twice that value.<br/>
\begin{equation}
    p\text{-value} = 2 \times (1 - T_{\text{CDF}}(abs(t_stat), df))
\end{equation}

where abs(x) is the absolute value of x, df are the degrees of freedom, and $T_{\text{CDF}}$ represents the Cumulative Distribution Function of the t-distribution.<br />

Scipy makes our task simple, as probability distributions have included the method cdf. See the documentation  https://tinyurl.com/yaake63s. 

Start by computing the the number of degrees of freedom ($df$), which are given by 

\begin{equation}
    df = n_1 + n_2 - 2
\end{equation}

In [19]:
df = n1 + n2 - 2
print(df)

98


Finally we need to estimate the p-value, save it in variable p-value

In [20]:
p = stats.t.sf(np.abs(t_stat), df)*2
print(p)

0.8444461923040681


Scipy already includes a function that performs the t-test that we have done step by step in this homework assignment. See the documentation of Scipy two sample t-test at  https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html. In the cell bellow repeat the t-test using the Scipy method, and compare the obtained p-values.

In [21]:
stats.ttest_ind(d1,d2)

Ttest_indResult(statistic=0.19673006785551048, pvalue=0.8444461923040681)

Finally, write down a function named twosample_ttest that takes two samples of the same size and returns the p-value, the t-statistics, and the degrees of freedom using all the code you implemented above. Note that if the samples are of different size you should return an error.

In [22]:
def twosample_ttest(dist1,dist2):
    #write your code here
    """This function takes 2 arrays with the same size as arguement
    and calculate a t-test. It returns the p-value, t-stattistics and degree of freedom.
    It will return an error is the 2 input array aren't the same size"""
    if not (np.prod(dist1.shape) == np.prod(dist2.shape)):
        return "error: Ensure your 2 input array are the same size"
    else:
        t = ((np.mean(dist1))-(np.mean(dist2)))/(np.sqrt((((np.std(dist1,ddof=1))**2)/(len(dist1)))+(((np.std(dist2,ddof=1))**2)/(len(dist2)))))
        df = (len(dist1)) + (len(dist2)) - 2
        p = stats.t.sf(np.abs(t), df)*2
        return {"p-value": p, "t-statistics":t, "df": df}

test your function bellow, for two random data with same size and standard deviation, but different means sets samples from a normal distribution.

In [23]:
# To test the function created calculate the t-statistics of 2 arrays

# create first array as test1
test1 = stats.norm.rvs(loc=0.72, scale=1.0, size=30)

#create second array as test2
test2 = stats.norm.rvs(loc=0.72, scale=1.0, size=30)

# using the twosample_ttest function to calculate he t-stats and p-palue
twosample_ttest(test1,test2)

{'p-value': 0.7640594707496929, 't-statistics': -0.3015687282100394, 'df': 58}